### ISSUE TITLE
The wrapper identifies the output file as the input source file

### ISSUE THREAD

**Issue by mupfdev** [libav/c99-to-c89#24]
Hello,
this project is incredibly interesting for homebrew development for the Nokia N-Gage, as we are currently tied to a very early version of GCC. However, the wrapper does not seem to work as long as an output file is specified via CMake:

`... -DRENDERER_SOFTWARE -w -O3 -o CMakeFiles\game.dir\src\wipeout\camera.c.obj -c C:\Development\Projects\ngage-toolchain\projects\wipeout\src\wipeout\camera.c`

This throws the following error message:
`CMakeFiles\game.dir\src\wipeout\camera.c.obj_preprocessed.c: No such file or directory`

I can reproduce the problem on the command line. If I write the entire command there without the source file in quotes, the wrapper works perfectly. Unfortunately, I have not yet been able to get CMake to adjust the generated prompt accordingly.

Is this project still supported? Do you have a tip how I can fix the problem to use the wrapper together with a quite old version of GCC?

Best regards,
Michael

**Comment by rbultje** [comment]
Hi Michael,

thanks for your interest. This project was very specifically written to help compile FFmpeg with pre-C99 versions of MSVC. I don't think I ever tested it with early gcc versions. Since MSVC nowadays has proper C99 support, I don't support this project anymore. (I don't know if others still use this for their own purposes.)

Best,
Ronald

**Comment by mupfdev** [comment]
Thanks for the quick reply, I try to fix the wrapper myself. 👍

**Comment by mupfdev** [comment]
I recompiled the binary using Visual Studio 2022 as a x64 executable. For some reason, it works now.
